### ISSUE TITLE
Luego de correr la template, copiar el .rbenv-vars.example en .rbenv-vars

### ISSUE THREAD

**Issue by juliogarciag** [platanus/rails_template#5]
Mi di cuenta que cada vez que corría la template, tenía que hacer `cp .rbenv-vars.example .rbenv-vars`. Entiendo que llenar el .rbenv-vars es un paso requerido cada vez que alguien clona el proyecto, pero de repente sería bueno evitar ese paso que siempre se hace. ¿Qué opinan?

**Comment by ldlsegovia** [comment]
agree

**Comment by blackjid** [comment]
:+1:
